[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "vtool"
authors = [{name = "Louis Vottero", email = "louis.vot@gmail.com"}]
dynamic = ["version", "description"]